import json, os

def read_missing_components_report(report_path: str, max_components: int = 10) -> dict:
    """
    Reads a missing-component audit JSON file and returns a concise summary
    suitable for LLM consumption.

    Args:
        report_path (str): Path to the JSON report generated by find_events_with_missing_components.
        max_components (int): Limit number of components returned to keep output concise.

    Returns:
        dict: A structured summary like:
            {
              "component_count": 3,
              "components": [
                {"id": "5-1", "missing_events": [12, 13]},
                {"id": "5-2", "missing_events": [44, 45]}
              ],
              "truncated": true
            }
    """
    print(f"--- TOOL: Reading report from {report_path} ---")

    if not os.path.exists(report_path):
        return {"error": f"Report file not found at {report_path}"}

    try:
        with open(report_path, "r") as f:
            data = json.load(f)
    except Exception as e:
        return {"error": f"Failed to parse JSON: {e}"}

    components = [
        {"id": k, "missing_events": v.get("missing_events_list", [])}
        for k, v in data.items()
    ]

    components = sorted(components, key=lambda x: len(x["missing_events"]), reverse=True)

    if max_components is None or (isinstance(max_components, int) and max_components <= 0):
        truncated = False
    else:
        truncated = len(components) > max_components
        if truncated:
            components = components[:max_components]

    return {
        "component_count": len(data),
        "components": components,
        "truncated": truncated
    }
